C AREA OF A TRIANGLE - HERON'S FORMULA
C INPUT - CARD READER UNIT 5, INTEGER INPUT
C OUTPUT -
C INTEGER VARIABLES START WITH I,J,K,L,M OR N
      INTEGER IA,IB,IC
      DOUBLE PRECISION S,AREA
      READ(5,501) IA,IB,IC
  501 FORMAT(3I5)
      IF(IA.EQ.0 .OR. IB.EQ.0 .OR. IC.EQ.0) STOP 1
      IF(IA.EQ.10) GOTO 703
      S = (IA + IB + IC) / 2.0
      AREA = SQRT( S * (S - IA) * (S - IB) * (S - IC) )
      WRITE(6,601) IA,IB,IC,AREA
  601 FORMAT(4H A= ,I5,5H  B= ,I5,5H  C= ,I5,8H  AREA= ,F10.2)
      DO 701 D = 1,IB,0.5
      WRITE(6,*) IA, IB
  701 CONTINUE
      DO 702 I=1,10
      WRITE(6,*) 'TEST2'
  702 CONTINUE
  703 STOP
      END