C AREA OF A TRIANGLE - HERON'S FORMULA
C INPUT - CARD READER UNIT 5, INTEGER INPUT
C OUTPUT -
C INTEGER VARIABLES START WITH I,J,K,L,M OR N
      INTEGER IA,IB,IC
      DOUBLE PRECISION S,AREA
      READ(5,501) IA,IB,IC
  501 FORMAT(3I5)
      IF(IA.EQ.0 .OR. IB.EQ.0 .OR. IC.EQ.0) STOP 1
      IF(IA.EQ.10) GOTO 703
      S = (IA + IB + IC) / 2.0
      AREA = SQRT( S * (S - IA) * (S - IB) * (S - IC) )
      WRITE(6,601) IA,IB,IC,AREA
  601 FORMAT(4H A= ,I5,5H  B= ,I5,5H  C= ,I5,8H  AREA= ,F10.2)
  703 STOP
      END

      SUBROUTINE PPRNT(P,N,ID)
      DIMENSION P(ID,N)
      IGO=1
      NEND=0
    1 NBEG=NEND+1
      NEND=NEND+6
      IF(NEND.LT.N) GO TO 3
    2 NEND=N
      IGO=2
    3 WRITE(5,4)((K),K=NBEG,NEND)
    4 FORMAT(1H0,10X,6(5X,I3,2X))
      WRITE(5,5) 
    5 FORMAT(1H )
      DO 6 I=1,N
    6 WRITE(5,7) I,(P(I,J),J=NBEG,NEND)   
    7 FORMAT(1H ,I8,2X,6F10.5)
      GOTO 1
    8 RETURN
      END